// You are given two strings, s and t which only consist of lowercase letters. 
// t is generated by shuffling the letters in s as well as potentially adding 
// an additional random character. Return the letter that was randomly added 
// to t if it exists, otherwise, return ''.
// Note: You may assume that at most one additional character can be added to t.

#include <cstdio>
#include <string>
#include <map>
using namespace std;

/*
 * Solution #1: We can a use a map to count the frequency
 * of each letter. Since t was generated by shuffling s,
 * then the frequency of each letter should be even except
 * for the added letter.
 *
 * Time complexity: O(n) | Space complexity: O(n)
 * where n is the size of the string s and the size of the string t.
 * the time complexity and space complexity is O(n), because in
 * the worst case the length of the string t is equal to n + 1.
 * Since we drop constants, we get that the space and time
 * complexity is: O(n + n) = O(2n) = O(n). :)
 */
char spot_difference(string s, string t) {

    map<char, int> histogram;
    for (char c : s)
        histogram[c]++;
    for (char c : t)
        histogram[c]++;
    // Find which letter has an odd frequency.
    // This is the letter that has been added to t
    for (auto p : histogram)
        if (histogram[p.first] & 1)
            return p.first;

    return '\0';
}

/*
 * Solution #2: We can use the bitwise-XOR to spot the difference.
 * The XOR operation will cancel characters that are equal, therefore
 * the result will be the only character that is different or 0 if 
 * all characters are the same.
 *
 * Time complexity: O(n) | Space complexity: O(1)
 * where n is the size of the string s and t.
 */
char spot_difference_xor(string s, string t) {
    
    char result = 0;
    for (int i = 0; i < s.length(); ++i)
        result ^=   s[i] ^ t[i];
    if (s.length() < t.length()) 
        result ^= t.back();

    return result;
}


int main() {
    // Test cases 
    assert (spot_difference("foobar", "barfoot") == 't');
    assert (spot_difference("ide", "idea") == 'a');
    assert (spot_difference("coding", "ingcod") == '\0');
    assert (spot_difference("abacaba", "aabacaba") == 'a');
    printf("YAY! Passed all tests! :P\n");

    assert (spot_difference_xor("foobar", "barfoot") == 't');
    assert (spot_difference_xor("ide", "idea") == 'a');
    assert (spot_difference_xor("coding", "ingcod") == '\0');
    assert (spot_difference_xor("abacaba", "aabacaba") == 'a');
    printf("YAY! Passed all tests! :P\n");

    return 0;

}
